name: Tests MacOSX

on:
  push:
  pull_request:
    
jobs:
  build_physimess:

    runs-on: macos-11

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run : brew install gcc@10

    - name: Build PhysiMeSS
      run: |
        make PHYSICELL_CPP=g++-10
        
    - name: Run all examples
      run: |
        ./project config/mymodel.xml

  build_physiboss_cell_lines:

    runs-on: macos-11

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run : brew install gcc@11
      
    - name: Build PhysiBoSS cell lines project
      run: |
        make physiboss-cell-lines-sample
        make clean
        make PHYSICELL_CPP=g++-11
        
    - name: Run PhysiBoSS cell lines project
      run: |
        ./PhysiBoSS_Cell_Lines