name: Tests Windows

on:
  push:
  pull_request:
    
jobs:
  build:

    runs-on: windows-latest
    
    defaults:
      run:
        shell: msys2 {0}
        
    steps:
    - uses: actions/checkout@v2
    
    - uses: msys2/setup-msys2@v2
      with:
        update: true
        install: base-devel gcc make diffutils mingw-w64-x86_64-toolchain
        
    - name: Build PhysiMeSS
      run: |
        make
        
    - name: Run all examples
      run: |
        .\\project config\\mymodel.xml
