name: Tests Ubuntu

on:
  push:
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Build PhysiMeSS
      run: |
        make 
        
    - name: Run all examples
      run: |
        ./project config/mymodel.xml
        
    - name: Run PhysiBoSS cell lines project
      run: |
        ./PhysiBoSS_Cell_Lines